// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoProjectServer.Context;

#nullable disable

namespace ToDoProjectServer.Migrations
{
    [DbContext(typeof(TodoAppContext))]
    [Migration("20231014192135_mg1")]
    partial class mg1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoProjectServer.Model.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Work")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Work")
                        .IsUnique();

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCompleted = false,
                            Work = "Get to work"
                        },
                        new
                        {
                            Id = 2,
                            IsCompleted = false,
                            Work = "Pick up groceries"
                        },
                        new
                        {
                            Id = 3,
                            IsCompleted = false,
                            Work = "Go home"
                        },
                        new
                        {
                            Id = 4,
                            IsCompleted = false,
                            Work = "Fall asleep"
                        },
                        new
                        {
                            Id = 5,
                            IsCompleted = true,
                            Work = "Get up"
                        },
                        new
                        {
                            Id = 6,
                            IsCompleted = true,
                            Work = "Brush teeth"
                        },
                        new
                        {
                            Id = 7,
                            IsCompleted = true,
                            Work = "Take a shower"
                        },
                        new
                        {
                            Id = 8,
                            IsCompleted = true,
                            Work = "Check e-mail"
                        },
                        new
                        {
                            Id = 9,
                            IsCompleted = true,
                            Work = "Walk dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
